config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'welcome#index'
  
    # Users
    devise_for :users
    
    #Products
    resources :products do
      member do
        get "delete"
      end
    end

    # Clients
    resources :clients do
      member do
        get "delete"
      end
    end

    # Stores
    resources :stores do
      member do
        get "delete"
      end
    end
  end
end

app/models/store.rb
class Store < ApplicationRecord
  include PgSearch::Model
  
  # Relations
  belongs_to :store_type
  has_many :store_users, inverse_of: :store
  has_many :users, :through => :store_users
  has_many :clients

  # Validations
  validates_presence_of :name, :cuit, :address, :store_type

  # Delegations
  delegate :name, to: :store_type, prefix: true

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [ 
      :sorted_by,
      :search
    ]
  )
  
  # Scopes
  pg_search_scope :search,
    against: [:name],
    :using => { :tsearch => {:prefix => true} }, # Buscar coincidencia desde las primeras letras.
    :ignoring => :accents # Ignorar tildes.

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/s
      # Ordenamiento por fecha de creación
      order("stores.created_at #{ direction }")
    else
      # Si no existe la opcion de ordenamiento se levanta la excepcion
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }
end

app/models/store_type.rb
class StoreType < ApplicationRecord
  # Relations
  has_many :stores
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  before_action :set_store, only: [:show, :edit, :update, :destroy, :delete]

  # GET /stores
  # GET /stores.json
  def index
    authorize Store
    @filterrific = initialize_filterrific(
      Store,
      params[:filterrific],
      persistence_id: false,
      default_filter_params: {sorted_by: 'created_at_desc'},
      available_filters: [
        :sorted_by,
        :search,
      ],
    ) or return
    @stores = @filterrific.find.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  # GET /stores/1
  # GET /stores/1.json
  def show
  end

  # GET /stores/new
  def new
    @store = Store.new
    @store_types = StoreType.all
  end

  # GET /stores/1/edit
  def edit
    @store_types = StoreType.all
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'La tienda se ha creado correctamente.' }
        format.json { render :show, status: :created, location: @store }
      else
        @store_types = StoreType.all
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'La tienda se ha modificado correctamente.' }
        format.json { render :show, status: :ok, location: @store }
      else
        @store_types = StoreType.all
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store.destroy
    respond_to do |format|
      format.html { redirect_to stores_url, notice: 'La tienda se ha eliminado correctamente.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_store
      @store = Store.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def store_params
      params.require(:store).permit(:name, :cuit, :address, :description, :store_type_id)
    end
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/stores/_form.html.erb
<%= simple_form_for(@store) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="card-body">
    <div class="form-inputs">
      <%# Name %>
      <%= f.input :name, label: "Nombre" %>

      <%# Store type %>
      <div class="form-group">
        <%= f.input :store_type_id,
          collection: @store_types,
          required: true,
          :input_html => {
            title: "Seleccionar tipo",
            include_blank: false,
            class: 'selectpicker',
            "data-width"=>"100%",
            "data-size"=>"10",
          } 
        %>
      </div>

      <%# CUIT %>
      <%= f.input :cuit %>

      <%# Address %>
      <%= f.input :address %>

      <%# Description %>
      <%= f.input :description %>
    </div>
  </div>

  <div class="card-footer">
    <div class="form-actions text-right">
      <%= link_to t('actions.back'), stores_path, class: 'btn btn-light mr-2' %>
      <%= f.button :submit, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/stores/_header.html.erb
<% content_for :page_header do %>
  <%# Stores %>
  <li class="nav-item <%= active_action('index') %>">
    <%= link_to stores_path, class: "nav-link" do %>
      <%= fa_icon "store-alt" %>
      <%= Store.model_name.human(count: 2).humanize %>
    <% end %>
  </li>

  <%# New %>
  <li class="nav-item <%= active_action('new') %>">
    <%= link_to new_store_path, class: "nav-link text-primary" do %>
      <%= fa_icon "plus" %>
      <%= t('actions.add', model: Store.model_name.human) %>
    <% end %>
  </li>
<% end %>

app/views/stores/_list.html.erb
<div id="filterrific_results">
  <div class="card">
    <table class="table table-hover">
      <thead>
        <tr>
          <th><%= Store.human_attribute_name(:name) %></th>
          <th><%= Store.human_attribute_name(:users_count) %></th>
          <th><%= Store.human_attribute_name(:clients_count) %></th>
          <th><%= Store.human_attribute_name(:type) %></th>
          <th><%= Store.human_attribute_name(:created_at) %> <%= fa_icon "calendar" %></th>
          <th><%= Store.human_attribute_name(:updated_at) %> <%= fa_icon "calendar" %></th>
          <th></th>
        </tr>
      </thead>
      <tbody id="stores">
        <%= render @stores %>
      </tbody>
    </table>
  </div>
  <div id="page_links">
    <%= will_paginate @stores, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/stores/_store.html.erb
<tr id="store_<%= store.id %>">
  <!-- Store: name -->
  <td>
    <%= store.name %>
  </td>
  
  <!-- Store: user count -->
  <td>
    <span class="badge badge-info">
      <%= store.users_count %>
    </span>
  </td>

  <!-- Store: client count -->
  <td>
    <span class="badge badge-info">
      <%= store.clients_count %>
    </span>
  </td>

  <!-- Store: type -->
  <td>
    <%= store.store_type_name %>
  </td>

  <!-- Store: created at -->
  <td>
    <%= store.created_at.strftime("%d/%m/%y") %>
  </td>

  <!-- Store: updated at -->
  <td>
    <%= store.created_at.strftime("%d/%m/%y") %>
  </td>

  <!-- Action buttons -->
  <td class="mx-auto">
    <%= render(
            partial: 'shared/action_buttons',
            locals:{ 
                object: store, 
                show: true, 
                edit: true, 
                destroy: true
            }
        ) 
    %>
  </td>
</tr>

app/views/stores/delete.js.erb
// Style modal
$('.modal-header').addClass('bg-danger');
$('.modal-header').addClass('text-white');


// Add the dialog title
$('#dialog h5').html("<i class='fa fa-trash'></i>  <%= t("actions.trash") %>");

// Render the edit form
$('.modal-body').html('<%= t("messages.store.trash", name: @store.name )%>');

// Add form button
$('.modal-footer').html(
  "<button type='button' class='btn btn-default pull-left' data-dismiss='modal'><%= t("actions.back")%></button>"+
  "<a data-remote='true' data-method='delete' href='/stores/<%= @store.id %>>' data-dismiss='modal' class='btn commit btn-danger pull-right' rel='nofollow'><%= t("actions.confirm") %></a>"
);

// Show the dynamic dialog
$('#dialog').modal("show");

// Remove style
$('#dialog').on('hidden.bs.modal', function () {
  $('.modal-header').removeClass('bg-danger');
  $('.modal-header').removeClass('text-white');
});

app/views/stores/edit.html.erb
<%= render "header" %>

<div class="row">
  <div class="col-6 mx-auto">
    <div class="card">
      <div class="card-header bg-warning">        
        <h5 class="title">
          <%= fa_icon "edit" %> Editando tienda
        </h5>
      </div>
      <%= render 'form', store: @store %>
    </div>
  </div>
</div>

app/views/stores/index.html.erb
<%= render "header"%>

<% content_for :container do %>-fluid<% end %>

<!--Listado-->
<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-header info">
        <div class="row">
          <div class="col-5">
            <div class="pb-2 mb-2 border-bottom h5">
              <%= fa_icon "store-alt" %>
              <%= Store.model_name.human(count: 2).humanize %>
            </div>
          </div>
          <div class="col-1"><%= render_filterrific_spinner %></div>
          <div class="col-6">
            <%= form_for_filterrific @filterrific do |f| %>
              <div class="row">
                <div class="col-md-4">
                  <div class="input-group">
                    <%= f.text_field(
                      :search,
                      class: 'form-control border',
                      placeholder: Store.human_attribute_name(:name),
                      autocomplete: 'off',
                      ) %>
                  </div>
                </div>
                <div class="col-md-2">
                  <%= button_tag type: 'submit', class: "btn btn-info", id: "register-button", title: t("actions.tooltip.filter"), 
                    data: { toggle: 'tooltip', placement: 'top' }, 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i>".html_safe do %>
                    <%= fa_icon "filter" %>
                  <% end %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-body" id="stores-list">
        <%= render(
          partial: 'stores/list',
          locals: { stores: @stores }
        ) %>
      </div>
    </div>
  </div>
</div>

app/views/stores/index.js copy.erb
<% js = escape_javascript(
  render(partial: 'stores/list', locals: { stores: @stores })
) %>

$("#filterrific_results").html("<%= js %>");

app/views/stores/index.js.erb
<% js = escape_javascript(
  render(partial: 'stores/list', locals: { stores: @stores })
) %>

$("#filterrific_results").html("<%= js %>");

app/views/stores/new.html.erb
<%= render "header" %>

<div class="row">
  <div class="col-6 mx-auto">
    <div class="card">
      <div class="card-header bg-primary text-white">        
        <h5 class="title">
          <%= fa_icon "plus" %> Nueva tienda
        </h5>
      </div>
      <%= render 'form', store: @store %>
    </div>
  </div>
</div>

app/views/stores/show.html.erb
<%= render "header" %>

<div class="row">
  <div class="col-6 mx-auto">
    <div class="card">
      <div class="card-header bg-secondary text-white">        
        <h5 class="title">
          <%= fa_icon "eye" %> Viendo tienda
        </h5>
      </div>
      <div class="card-body fixed-panel-store">
        <p>
          <strong>Nombre:</strong>
          <%= @store.name %>
        </p>

        <p>
          <strong>CUIT:</strong>
          <%= @store.cuit %>
        </p>

        <p>
          <strong>Domicilio:</strong>
          <%= @store.address %>
        </p>

        <p>
          <strong>Descripción:</strong>
          <%= @store.description %>
        </p>

        <p>
          <strong>Tipo:</strong>
          <%= @store.store_type_name %>
        </p>
      </div> 
      <div class="card-footer text-right">
        <%= link_to stores_path, class: "btn btn-light mr-1" do %>
          Volver
        <% end %>
      </div>
    </div>
  </div>
</div>