config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'welcome#index'
  
    # Users
    devise_for :users
    
    #Products
    resources :products do
      member do
        get "delete"
      end
    end

    # Clients
    resources :clients do
      member do
        get "delete"
      end
    end

    # Stores
    resources :stores do
      member do
        get "delete"
      end
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  include PgSearch::Model

  # Validations
  validates_presence_of :name, :code, :cost_price, :sale_price, :store_price
  validates_uniqueness_of :code

  filterrific(
    default_filter_params: { sorted_by: 'created_at_desc' },
    available_filters: [ 
      :sorted_by,
      :search
    ]
  )

  # Scopes
  pg_search_scope :search,
    against: [:name, :code],
    :using => { :tsearch => {:prefix => true} }, # Buscar coincidencia desde las primeras letras.
    :ignoring => :accents # Ignorar tildes.

  scope :sorted_by, lambda { |sort_option|
    # extract the sort direction from the param value.
    direction = (sort_option =~ /desc$/) ? 'desc' : 'asc'
    case sort_option.to_s
    when /^created_at_/s
      # Order by created at
      order("products.created_at #{ direction }")
    else
      # Si no existe la opcion de ordenamiento se levanta la excepcion
      raise(ArgumentError, "Invalid sort option: #{ sort_option.inspect }")
    end
  }

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy, :delete]

  # GET /products
  # GET /products.json
  def index
    authorize Product
    @filterrific = initialize_filterrific(
      Product,
      params[:filterrific],
      persistence_id: false,
      default_filter_params: {sorted_by: 'created_at_desc'},
      available_filters: [
        :sorted_by,
        :search,
      ],
    ) or return
    @products = @filterrific.find.order(created_at: :desc).paginate(page: params[:page], per_page: 20)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    authorize @product
  end

  # GET /products/new
  def new
    authorize Product
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
    authorize @product
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)
    authorize @product

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    authorize @product

    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    authorize @product
    
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :code, :cost_price, :sale_price, :store_price)
    end
end

app/views/products/_filter.html.erb
<%= form_for_filterrific @filterrific do |f| %>
  <div class="row">
    <div class="col-md-4">
      <div class="input-group">
        <%= f.text_field(
          :search,
          class: 'form-control border',
          placeholder: t('placeholder' , model1: Product.human_attribute_name(:name), model2: Product.human_attribute_name(:code)),
          autocomplete: 'off',
          ) %>
      </div>
    </div>
    <div class="col-md-2">
      <%= button_tag type: 'submit', class: "btn btn-info", id: "register-button", title: t("actions.tooltip.filter"), 
        data: { toggle: 'tooltip', placement: 'top' }, 'data-disable-with' => "<i class='fa fa-spinner fa-spin'></i>".html_safe do %>
        <%= fa_icon "filter" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/products/_form.html.erb
<%= simple_form_for(@product) do |f| %>
  <div class="card-body">
    <%= f.error_notification %>
    <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :code %>
      <%= f.input :cost_price %>
      <%= f.input :sale_price %>
      <%= f.input :store_price %>
    </div>
  </div>

  <div class="card-footer">
    <div class="form-actions text-right">
      <%= link_to t('actions.back'), products_path, class: 'btn btn-light mr-2' %>
      <%= f.button :submit, class: 'btn btn-success' %>
    </div>
  </div>
<% end %>

app/views/products/_header.html.erb
<% content_for :page_header do %>
  <%# Stores %>
  <li class="nav-item <%= active_action('index') %>">
    <%= link_to stores_path, class: "nav-link" do %>
      <%= fa_icon "boxes" %>
      <%= Product.model_name.human(count: 2).humanize %>
    <% end %>
  </li>

  <%# New %>
  <li class="nav-item <%= active_action('new') %>">
    <%= link_to new_product_path, class: "nav-link text-primary" do %>
      <%= fa_icon "plus" %>
      <%= t('actions.add', model: Product.model_name.human) %>
    <% end %>
  </li>
<% end %>

app/views/products/_list.html.erb
<div id="filterrific_results">
  <div class="card">
    <table class="table table-hover table-sm">
      <thead>
        <tr>
          <th><%= Product.human_attribute_name(:name) %></th>
          <th><%= Product.human_attribute_name(:code) %></th>
          <th><%= Product.human_attribute_name(:cost_price) %></th>
          <th><%= Product.human_attribute_name(:sale_price) %></th>
          <th><%= Product.human_attribute_name(:store_price) %></th>
          <th class="text-center" style="width: 1%;"><%= t :action %></th>
        </tr>
      </thead>
      <tbody id="products">
        <%=  simple_form_for(Product.new, :url => products_path(format: :csv),
          :action => :index,
          :method => :get,
          html: { id: :csv_form }) do |form| %>
          
          <%= render @products, :f => form  %>
        <% end%>
      </tbody>
    </table>
  </div>
</div>

app/views/products/_product.html.erb
<tr id="product_<%= product.id %>">  
  <!-- Name -->
  <td>
    <%= product.name %>
  </td>

  <!-- Code -->
  <td>
    <%= product.code %>
  </td>
  
  <!-- Cost price -->
  <td>
    <%= format_number(product.cost_price) %>
  </td>
  
  <!-- Sale price -->
  <td>
    <%= format_number(product.sale_price) %>
  </td>
  
  <!-- Store price -->
  <td>
    <%= format_number(product.store_price) %>
  </td>

  <!-- Action buttons -->
  <td class="mx-auto">
    <%= render(
            partial: 'shared/action_buttons',
            locals:{ 
                object: product, 
                show: true, 
                edit: true, 
                destroy: true
            }
        ) 
    %>
  </td>
</tr>

app/views/products/delete.js.erb
// Style modal
$('.modal-header').addClass('bg-danger');
$('.modal-header').addClass('text-white');


// Add the dialog title
$('#dialog h5').html("<i class='fa fa-trash'></i> <%= t("actions.trash") %>");

// Render the edit form
$('.modal-body').html("<%= t("messages.product.trash", name: @product.name )%>");

// Add form button
$('.modal-footer').html(
  "<button type='button' class='btn btn-default pull-left' data-dismiss='modal'><%= t("actions.back") %></button>"+
  "<a data-remote='true' data-method='delete' href='/products/<%= @product.id %>>' data-dismiss='modal' class='btn commit btn-danger pull-right' rel='nofollow'><%= t("actions.confirm") %></a>"
);

// Show the dynamic dialog
$('#dialog').modal("show");

// Remove style
$('#dialog').on('hidden.bs.modal', function () {
  $('.modal-header').removeClass('bg-danger');
  $('.modal-header').removeClass('text-white');
});

app/views/products/edit.html.erb
<%= render "header" %>

<% content_for :container do %>-fluid<% end %>

<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-header bg-warning">
        <div class="row">
          <div class="col-md-8">
            <h5 class="title text-capitalize">
              <%= fa_icon "edit" %>
              <%= t('actions.edit' , model: Product.model_name.human) %>
            </h5>
          </div>
        </div>
      </div>
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<% render "header" %>

<% content_for :container do %>-fluid<% end %>

<!--Listado-->
<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-header">
        <div class="row">
          <div class="col-5">
            <div class="pb-2 mb-2 border-bottom h5">
              <%= fa_icon "boxes" %>
              <%= Product.model_name.human(count: 2).humanize %>
            </div>
          </div>
          <div class="col-1"><%= render_filterrific_spinner %></div>
          <div class="col-6">
            <%= render "filter" %>
          </div>
        </div>
      </div>
      <div class="card-body" id="products-list">
        <%= render(
          partial: 'products/list',
          locals: { products: @products }
        ) %>
      </div>
    </div>
    <%= will_paginate @products, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/products/new.html.erb
<%= render "header" %>

<% content_for :container do %>-fluid<% end %>

<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-header bg-primary text-white">
        <div class="row">
          <div class="col-md-8">
            <h5 class="title text-capitalize">
              <%= t('actions.new' , model: Product.model_name.human) %>
            </h5>
          </div>
        </div>
      </div>
      <%= render 'form', product: @product %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<%= render "header" %>

<% content_for :container do %>-fluid<% end %>

<div class="row">
  <div class="col-12">
    <div class="card mb-3">
      <div class="card-header bg-secondary text-white">
        <div class="row">
          <div class="col-md-8">
            <h5 class="title text-capitalize">
              <%= fa_icon "eye" %>
              <%= t('actions.show' , model: Product.model_name.human) %>
            </h5>
          </div>
        </div>
      </div>
      <div class="card-body">
        <p>
          <strong><%= Product.human_attribute_name(:name) %>:</strong>
          <%= @product.name %>
        </p>

        <p>
          <strong><%= Product.human_attribute_name(:code) %>:</strong>
          <%= @product.code %>
        </p>

        <p>
          <strong><%= Product.human_attribute_name(:cost_price) %>:</strong>
          <%= @product.cost_price %>
        </p>

        <p>
          <strong><%= Product.human_attribute_name(:sale_price) %>:</strong>
          <%= @product.sale_price %>
        </p>

        <p>
          <strong><%= Product.human_attribute_name(:store_price) %>:</strong>
          <%= @product.store_price %>
        </p>

      </div>
      
      <div class="card-footer text-right">
        <%= link_to t('actions.back'), products_path, class: "btn btn-light mr-2" %>
        <%= link_to t('actions.tooltip.edit'), edit_product_path(@product), class: "btn btn-warning" %>
      </div>
    </div>
  </div>
</div>