config/routes.rb
Rails.application.routes.draw do
  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    root 'welcome#index'
  
    # Users
    devise_for :users
    
    #Products
    resources :products do
      member do
        get "delete"
      end
    end

    # Clients
    resources :clients do
      member do
        get "delete"
      end
    end

    # Stores
    resources :stores do
      member do
        get "delete"
      end
    end
  end
end

app/views/layouts/_flash_notices.html.erb
<% flash.each do |type, message| %>
  <div class='alert <%= bootstrap_class_for(type) %> alert-dismissible' role='alert'><button class='close' data-dismiss='alert'>×</button><%= message.html_safe %></div>
<% end %>

app/views/layouts/_login_items.html.erb
<% if user_signed_in? %>
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true">
      <%= current_user.email %>
    </a>
    <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
      <div class="dropdown-divider"></div>
      <%= link_to destroy_user_session_path, :method => :delete, class: "dropdown-item" do %>
        <%= fa_icon "power-off" %>
        Cerrar sesión
      <% end %>
    </div>
  </li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= yield :page_header %>
    </ul>
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <%= render 'layouts/login_items'%>
    </ul>
  </div>
</nav>

app/views/layouts/_side_navigation.html.erb
<!-- Sidebar -->
<div class="bg-light border-right navbar-light" id="sidebar-wrapper">
  <!--Brand-->
  <div class="sidebar-heading d-flex justify-content-between">    
    <%= link_to root_path, data: { turbolinks: false }, class: "navbar-brand d-flex align-item-center #{active_class('welcome')}" do %>
      <%= image_tag("LogoStockManage.svg", size: "50x50", alt: "Logo Lighuen", class: 'logo') %>
      stockmanage
    <% end %>

    <button class="btn btn-light" id="menu-toggle"><%= fa_icon "bars" %></button>
  </div>

  <!--Menu list-->
  <div class="list-group list-group-flush">
    <%# Welcome %>
    <%= link_to root_path, class: "list-group-item list-group-item-action list-custom bg-light #{active_class('welcome')}" do %>
      <span class="sb-icon">
        <%= fa_icon "home" %> 
      </span>
      <span class="sb-title">Inicio</span>
    <% end %>
    
    <%# Products %>
    <%= link_to products_path, class: "list-group-item list-group-item-action list-custom bg-light #{active_class('products')}" do %>
      <span class="sb-icon">
        <%= fa_icon "boxes" %>
      </span>
      <span class="sb-title text-capitalize"><%= Product.model_name.human(count: 2) %></span>
    <% end %>

    <%# Clients %>
    <%= link_to clients_path, class: "list-group-item list-group-item-action list-custom bg-light #{active_class('clients')}" do %>
      <span class="sb-icon">
        <%= fa_icon "address-card" %>
      </span>
      <span class="sb-title">Clientes</span>
    <% end %>

    <%# Stores %>
    <%= link_to stores_path, class: "list-group-item list-group-item-action list-custom bg-light #{active_class('stores')}" do %>
      <span class="sb-icon">
        <%= fa_icon "store-alt" %>
      </span>
      <span class="sb-title">Tiendas</span>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stockmanage</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag 'LogoStockManage.png' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <style>
    @media (max-width: 769px) {
      body {
        background-color: #1a2849;
      }
    }
    @media (min-width: 769px) {
      body {
        background-image: url("<%= asset_path('stockmanage-bg.jpg') %>");
      }
    }
  </style>

  <body>
    <div class="d-flex" id="wrapper">
      <!-- Sidebar -->
      <% if user_signed_in? %>
        <%= render 'layouts/side_navigation' %>
      <% end %>

      <!-- Page Content -->
      <div id="page-content-wrapper">
        <% if user_signed_in? %>
          <!-- Navbar -->
          <%= render 'layouts/navigation' %>
        <% end %>
        <div class="mt-3 container<%= yield :container %>">
          
          <!-- Flash message -->
          <div id="flash_messages" class="mx-auto d-block">
            <%= render "layouts/flash_notices" %>
          </div>

          <!-- Modal -->
          <%= render "shared/dialog" %>

          <!-- Main yield -->
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>